### ISSUE TITLE
Instruction Datasets

### ISSUE THREAD

**Issue by daydayupzzl** [PKU-YuanGroup/ProLLaMA#1]
Your work is verry interesting! Are the preprocessed instruction datasets used in stage 2(1) and 2(2) publicly available ? thanks a lot !

**Comment by Lyu6PosHao** [comment]
Thanks a lot for your recognition to our work! We will consider making the dataset public after a period of time.

**Comment by JinyuanSun** [comment]
Can this model only generate sequences for a given superfamily or predict the superfamily to which a sequence belongs? Can this model predict effects caused by mutations?

**Comment by Lyu6PosHao** [comment]
Yes, it is currently.
As for mutation effects, perhaps it can be measured by the perplexity of the model output. We will give a script.

**Comment by Lyu6PosHao** [comment]
Hello @JinyuanSun, we have given a script to measure mutation effects. It is in /scirpts/mutation.py.

Feel free to let me know if you have any questions.

**Comment by Lyu6PosHao** [comment]
@daydayupzzl Hello, we have opensourced the instruction dataset on [HuggingFace](https://huggingface.co/datasets/GreatCaptainNemo/instruction_dataset). Please check it.
