### ISSUE TITLE
为什么第一阶段可训练参数量更大

### ISSUE THREAD

**Issue by 21-10-4** [PKU-YuanGroup/ProLLaMA#12]
![image](https://github.com/user-attachments/assets/1f77e8d7-0e12-4431-b485-ad00aaafa791)
根据PVP（词汇表压缩得更少），不是应该第二阶段更大吗？
期待您的解答。

**Comment by Lyu6PosHao** [comment]
您好，因为第一阶段时要训练 embedding层+LoRA adapter，而第二阶段只训练LoRA adapter。而PVP只会减少embedding层的参数量。
