### ISSUE TITLE
模型微调的问题

### ISSUE THREAD

**Issue by realHXiao** [PKU-YuanGroup/ProLLaMA#4]
您好。我想将您的模型（来源于https://hf-mirror.com/GreatCaptainNemo/ProLLaMA ）微调成用于预测蛋白质和小分子之间相互作用的参数的模型。

模型微调工具为LLaMA-Factory。微调参数设置如下：
```
CUDA_VISIBLE_DEVICES=0 /opt/llama_factory/bin/python src/train_bash.py \
--stage sft \
--model_name_or_path pretrained_models/ProLLaMA/ \
--do_train \
--dataset llama_input_Smiles_Sequence \
--finetuning_type lora  \
--lora_target q_proj,v_proj \
--output_dir output_finetuning_models/ProLLaMA/lora/sft \
--overwrite_cache \
--per_device_train_batch_size 1 \
--per_device_eval_batch_size 4  \
--gradient_accumulation_steps 16  \
--preprocessing_num_workers 16 \
--lr_scheduler_type cosine \
--logging_steps 10    \
--save_steps 10000   \
--learning_rate 5e-5   \
--max_grad_norm 0.5     \
--num_train_epochs 3   \
--evaluation_strategy no  \
--bf16 \
--template llama2 \
--overwrite_output_dir  \
--cutoff_len 1024  \
--quantization_bit 4 \
--plot_loss \
```

lora微调且合并模型之后，我用类似main.py中的代码进行了预测，得到如下结果：

![image](https://github.com/PKU-YuanGroup/ProLLaMA/assets/71002556/c832e26b-af92-4e24-99f1-eb941fd3042b)

我好像没有微调成功。

想请教一下您是怎样进行Stage II Again过程的。非常感谢！！

**Comment by Lyu6PosHao** [comment]
您好！可能的原因是您的数据集比较少、学习率比较低、或者数据集每条sample的格式和原ProLLaMA的格式不太一样。导致输出受到ProLLaMA原本执行的任务的干扰。
可能的解决方案：
1. 微调ProLLaMA_Stage_1而不是ProLLaMA，[详情可见](https://github.com/PKU-YuanGroup/ProLLaMA?tab=readme-ov-file#%EF%B8%8Fothers).  [HuggingFace Link
](https://huggingface.co/GreatCaptainNemo/ProLLaMA_Stage_1)
2. 使用Seq=\<xxx\>将蛋白质序列包裹起来，xxx为原始蛋白质序列。这样是为了使得数据格式一致。
3. 设计intruction tuning数据集时，建议instruction部分用一句话描述任务类型，input部分是分子和蛋白质序列，output是预期输出。我也建议用某种前后缀将分子包裹起来，比如Mol=\{xxx\}。
4. 如果您仍然想要微调ProLLaMA而不是ProLLaMA_Stage_1，建议增大学习率、每条sample的格式与论文中格式类似。

如果您还有疑惑，可以继续交流。
