### ISSUE TITLE
下游多任务上如何使用

### ISSUE THREAD

**Issue by Qiny-dl** [PKU-YuanGroup/ProLLaMA#6]
Prollama本质还是预测下一个token，在不同下游任务上如何使用提示学习的方法使用和评估、

**Comment by Lyu6PosHao** [comment]
Could you please provide a bit more detail about your question?

**Comment by Qiny-dl** [comment]
我想知道，在一些具体的下游任务上，如何制作我们的 微调数据集格式，可否给出一些具体任务的微调脚本，如 预测蛋白质的化学特性，疏水，亲油  以及一下两个蛋白质链的相互作用关系 最好可以给出建议的 输入数据具体格式

**Comment by Lyu6PosHao** [comment]
好的，我会给出数据集制作的代码，和训练代码。
不过大体来说，只要注意把蛋白质序列用Seq=<xxx>包裹一下（xxx为原蛋白质序列），其余的格式都输入数据的文本格式什么的，都是自由的。

**Comment by Lyu6PosHao** [comment]
你好，我们开源了二阶段用的指令微调数据集，可以参考下格式 [here](https://huggingface.co/datasets/GreatCaptainNemo/instruction_dataset)

**Comment by Qiny-dl** [comment]
感谢 我尝试一下
