### ISSUE TITLE
无条件生成

### ISSUE THREAD

**Issue by ZJL0111** [PKU-YuanGroup/ProLLaMA#7]
您好在利用ProLLaMA进行蛋白质的无条件生成时，模型的输入是什么呢？ 还有在无条件生成的对比实验中，基于ESM2的是如何实现的呢？

**Comment by Lyu6PosHao** [comment]
您好。无条件生成，就是让ProLLaMA_Stage1做推理，输入为"Seq=<"，详情见[this](https://github.com/PKU-YuanGroup/ProLLaMA?tab=readme-ov-file#%EF%B8%8Fothers)。

ESM2的生成，代码见[this](https://github.com/microsoft/evodiff/issues/29)。大概就是输入为全部是[MASK]的token串，让ESM2依次预测出所有[MASK]对应的氨基酸。

**Comment by ZJL0111** [comment]
> 您好。无条件生成，就是让ProLLaMA_Stage1做推理，输入为"Seq=<"，详情见[this](https://github.com/PKU-YuanGroup/ProLLaMA?tab=readme-ov-file#%EF%B8%8Fothers)。
> 
> ESM2的生成，代码见[this](https://github.com/microsoft/evodiff/issues/29)。大概就是输入为全部是[MASK]的token串，让ESM2依次预测出所有[MASK]对应的氨基酸。

多谢
