### ISSUE TITLE
ProLLaMA on Ollama

### ISSUE THREAD

**Issue by colbyford** [PKU-YuanGroup/ProLLaMA#9]
Hello,

I have just published a blog post that shows how to run your ProLLaMA model on [Ollama](https://ollama.com/).

https://blog.colbyford.com/deploy-protein-language-models-using-ollama-42c267e32ba5

My model conversion code: https://github.com/colbyford/ProLLaMA-on-Ollama

If you're interested, the Ollama team may host your model as one of the open-source models that is natively supported on their platform.

**Comment by Lyu6PosHao** [comment]
Hi,
Thanks a lot for your contribution! It's wonderful to see such detailed work on deploying our models using Ollama.
We would be delighted to have our model hosted on the Ollama platform. We could continue via email if further discussions are needed.
Thanks again!
